# Exploratory Data Analysis (EDA) on Open-Meteo Dataset

In [1]:
import pandas as pd
from src.enums import measurements, aq_keys

aq = pd.read_csv('02-28-open-meteo-2023-2026.csv')

## Understand air quality features
Identify what kind of information is in each column, such as measurement and description.

In [2]:
aq_measurements = {
    aq_keys['time']: measurements['interval'],
    aq_keys['us_aqi (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_pm2_5 (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_pm10 (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_nitrogen_dioxide (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_carbon_monoxide (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_ozone (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_sulphur_dioxide (USAQI)']: measurements['ordinal'],
    aq_keys['methane (μg/m³)']: measurements['ratio'],
    aq_keys['uv_index_clear_sky ()']: measurements['ratio'],
    aq_keys['uv_index ()']: measurements['ratio'],
    aq_keys['dust (μg/m³)']: measurements['ratio'],
    aq_keys['aerosol_optical_depth ()']: measurements['ratio'],
    aq_keys['ozone (μg/m³)']: measurements['ratio'],
    aq_keys['sulphur_dioxide (μg/m³)']: measurements['ratio'],
    aq_keys['nitrogen_dioxide (μg/m³)']: measurements['ratio'],
    aq_keys['carbon_dioxide (ppm)']: measurements['ratio'],
    aq_keys['pm2_5 (μg/m³)']: measurements['ratio'],
    aq_keys['carbon_monoxide (μg/m³)']: measurements['ratio'],
    aq_keys['pm10 (μg/m³)']: measurements['ratio']
}
aq_descriptions = {
    aq_keys['time']: "Time of the measurement.",
    aq_keys['us_aqi (USAQI)']: "Air Quality Index is the overall standardized levels of health risk or air pollution.",
    aq_keys['us_aqi_pm2_5 (USAQI)']: "AQI for PM2.5 particles.",
    aq_keys['us_aqi_pm10 (USAQI)']: "AQI for PM10 particles.",
    aq_keys['us_aqi_nitrogen_dioxide (USAQI)']: "AQI for Nitrogen Dioxide.",
    aq_keys['us_aqi_carbon_monoxide (USAQI)']: "AQI for Carbon Monoxide.",
    aq_keys['us_aqi_ozone (USAQI)']: "AQI for Ozone.",
    aq_keys['us_aqi_sulphur_dioxide (USAQI)']: "AQI for Sulphur Dioxide.",
    aq_keys['methane (μg/m³)']: "A potent greenhouse gas that increases ozone levels.",
    aq_keys['uv_index_clear_sky ()']: "Measurement of the intensity of ultraviolet radiation from the sun under clear sky conditions, high levels can cause sunburn and skin cancer.",
    aq_keys['uv_index ()']: "Measurement of the intensity of ultraviolet radiation from the sun, high levels can cause sunburn and skin cancer.",
    aq_keys['dust (μg/m³)']: "Dust particles in the air that can cause coughing, wheezing, and asthma attacks.",
    aq_keys['aerosol_optical_depth ()']: "Measure of how much sunlight is blocked by airborne particles. High AOD indicates high concentration of particulate matters (PM2.5 and PM10).",
    aq_keys['ozone (μg/m³)']: "Created by chemical reactions between oxides of nitrogen and sunlight, it is a powerful lung irritant that can trigger asthma.",
    aq_keys['sulphur_dioxide (μg/m³)']: "Produced by burning fossil fuels, it constricts airways and is particularly dangerous for people with asthma.",
    aq_keys['nitrogen_dioxide (μg/m³)']: "Vehicle emissions can cause airway inflammation.",
    aq_keys['carbon_dioxide (ppm)']: "Colorless gas produced by burning fossil fuels. Not harmful outdoors.",
    aq_keys['pm2_5 (μg/m³)']: "Tiny particles that can lodge deep in the lungs and enter the bloodstream.",
    aq_keys['carbon_monoxide (μg/m³)']: "Odorless gas from combustion, reduces oxygen delivery to organs.",
    aq_keys['pm10 (μg/m³)']: "Includes dust, pollen, mold and affects the upper respiratory tract."
}

aq.info()
pd.DataFrame({
    "Measurement Type": aq_measurements,
    "Description": aq_descriptions,
})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23208 entries, 0 to 23207
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             23208 non-null  object
 1   us_aqi (USAQI)                   23208 non-null  int64
 2   us_aqi_pm2_5 (USAQI)             23208 non-null  int64
 3   us_aqi_pm10 (USAQI)              23208 non-null  int64
 4   us_aqi_nitrogen_dioxide (USAQI)  23208 non-null  int64
 5   us_aqi_carbon_monoxide (USAQI)   23208 non-null  int64
 6   us_aqi_ozone (USAQI)             23208 non-null  int64
 7   us_aqi_sulphur_dioxide (USAQI)   23208 non-null  int64
 8   methane (μg/m³)                  11624 non-null  float64
 9   uv_index_clear_sky ()            23208 non-null  float64
 10  uv_index ()                      23208 non-null  float64
 11  dust (μg/m³)                     23208 non-null  int64
 12  aerosol_optical_depth ()         23208 non-null  float64
 13  ozone (μg/m³)                    23208 non-null  int64
 14  sulphur_dioxide (μg/m³)          23208 non-null  float64
 15  nitrogen_dioxide (μg/m³)         23208 non-null  float64
 16  carbon_dioxide (ppm)             11624 non-null  float64
 17  pm2_5 (μg/m³)                    23208 non-null  float64
 18  carbon_monoxide (μg/m³)          23208 non-null  int64
 19  pm10 (μg/m³)                     23208 non-null  float64
dtypes: float64(9), int64(10), object(1)
memory usage: 3.5+ MB

,Measurement Type,Description
time,interval,Time of the measurement.
us_aqi (USAQI),ordinal,Air Quality Index is the overall standardized ...
us_aqi_pm2_5 (USAQI),ordinal,AQI for PM2.5 particles.
us_aqi_pm10 (USAQI),ordinal,AQI for PM10 particles.
us_aqi_nitrogen_dioxide (USAQI),ordinal,AQI for Nitrogen Dioxide.
us_aqi_carbon_monoxide (USAQI),ordinal,AQI for Carbon Monoxide.
us_aqi_ozone (USAQI),ordinal,AQI for Ozone.
us_aqi_sulphur_dioxide (USAQI),ordinal,AQI for Sulphur Dioxide.
methane (μg/m³),ratio,A potent greenhouse gas that increases ozone l...
uv_index_clear_sky (),ratio,Measurement of the intensity of ultraviolet ra...
uv_index (),ratio,Measurement of the intensity of ultraviolet ra...
dust (μg/m³),ratio,Dust particles in the air that can cause cough...
aerosol_optical_depth (),ratio,Measure of how much sunlight is blocked by air...
ozone (μg/m³),ratio,Created by chemical reactions between oxides o...
sulphur_dioxide (μg/m³),ratio,"Produced by burning fossil fuels, it constrict..."
nitrogen_dioxide (μg/m³),ratio,Vehicle emissions can cause airway inflammation.
carbon_dioxide (ppm),ratio,Colorless gas produced by burning fossil fuels...
pm2_5 (μg/m³),ratio,Tiny particles that can lodge deep in the lung...
carbon_monoxide (μg/m³),ratio,"Odorless gas from combustion, reduces oxygen d..."
pm10 (μg/m³),ratio,"Includes dust, pollen, mold and affects the up..."

## Pre-narrow air quality data features
Based on feature descriptions, identify which features are unnecessary, and remove them to focus on relevant features and avoid wasting time.

In [3]:
# No column will be dropped.
aq_preview = aq.copy()
aq_preview['null_count'] = aq_preview.isnull().sum(axis=1)
aq_preview.sort_values('null_count', ascending=True).head(3).drop('null_count', axis=1)

,time,us_aqi (USAQI),us_aqi_pm2_5 (USAQI),us_aqi_pm10 (USAQI),us_aqi_nitrogen_dioxide (USAQI),us_aqi_carbon_monoxide (USAQI),us_aqi_ozone (USAQI),us_aqi_sulphur_dioxide (USAQI),methane (μg/m³),uv_index_clear_sky (),uv_index (),dust (μg/m³),aerosol_optical_depth (),ozone (μg/m³),sulphur_dioxide (μg/m³),nitrogen_dioxide (μg/m³),carbon_dioxide (ppm),pm2_5 (μg/m³),carbon_monoxide (μg/m³),pm10 (μg/m³)
11603,2024-10-26 11:00,61,61,23,6,5,18,4,1388.0,4.65,4.25,0,0.03,86,7.3,11.7,459.0,6.2,292,9.2
15475,2025-04-05 19:00,53,53,17,13,2,50,3,1454.0,0.00,0.00,3,0.10,67,5.5,25.9,463.0,14.3,335,17.7
15474,2025-04-05 18:00,53,53,16,9,2,50,3,1433.0,0.05,0.05,3,0.10,85,5.1,18.5,458.0,12.7,301,16.2