# Exploratory Data Analysis (EDA) on Respiratory Virus Dashboard Dataset

In [101]:
import pandas as pd
from src.enums import measurements, rv_keys

rv = pd.read_csv('02-28-respiratory-virus-dashboard-2023-2026.csv')

is_bay_area_region = rv[rv_keys['RPHO_REGION']] == 'Bay Area' # Only include the same region as the air quality dataset.
is_all_ages_age_group = rv[rv_keys['AGE_GRP']] == 'All Ages' # Only include all ages data, as it is an aggregate of all age groups and will be easier to stitch with the air quality dataset which is not age-specific.
rv = rv[is_bay_area_region & is_all_ages_age_group]

## Understand respiratory virus features
Identify what kind of information is in each column, such as measurement and description.

In [102]:
rv_measurements = {
    rv_keys['SEASON']: measurements['nominal'],
    rv_keys['AGE_GRP']: measurements['nominal'],
    rv_keys['RPHO_REGION']: measurements['nominal'],
    rv_keys['WEEKENDING']: measurements['interval'],
    rv_keys['MMWR_WEEK']: measurements['interval'],
    rv_keys['MMWR_YEAR']: measurements['interval'],
    rv_keys['COV_POSITIVES']: measurements['ratio'],
    rv_keys['COV_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['COV_TP']: measurements['ratio'],
    rv_keys['COV_TP_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_POSITIVES']: measurements['ratio'],
    rv_keys['FLU_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['FLU_TP']: measurements['ratio'],
    rv_keys['FLU_TP_LEVEL']: measurements['ordinal'],
    rv_keys['RSV_POSITIVES']: measurements['ratio'],
    rv_keys['RSV_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['RSV_TP']: measurements['ratio'],
    rv_keys['RSV_TP_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_A_TESTS']: measurements['ratio'],
    rv_keys['FLU_B_TESTS']: measurements['ratio'],
    rv_keys['COV_ED_VISITS']: measurements['ratio'],
    rv_keys['FLU_ED_VISITS']: measurements['ratio'],
    rv_keys['RSV_ED_VISITS']: measurements['ratio'],
    rv_keys['POP']: measurements['ratio'],
    rv_keys['COV_ADM']: measurements['ratio'],
    rv_keys['FLU_ADM']: measurements['ratio'],
    rv_keys['RSV_ADM']: measurements['ratio'],
    rv_keys['COV_ADM_RATE']: measurements['ratio'],
    rv_keys['FLU_ADM_RATE']: measurements['ratio'],
    rv_keys['RSV_ADM_RATE']: measurements['ratio'],
    rv_keys['COV_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['RSV_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['TOTAL_DEATHS']: measurements['ratio'],
    rv_keys['COV_DEATHS']: measurements['ratio'],
    rv_keys['FLU_DEATHS']: measurements['ratio'],
    rv_keys['RSV_DEATHS']: measurements['ratio'],
    rv_keys['COV_DEATHS_PER']: measurements['ratio'],
    rv_keys['FLU_DEATHS_PER']: measurements['ratio'],
    rv_keys['RSV_DEATHS_PER']: measurements['ratio'],
    rv_keys['SEASON_COV_PED_DEATHS']: measurements['ratio'],
    rv_keys['SEASON_FLU_PED_DEATHS']: measurements['ratio'],
    rv_keys['SEASON_RSV_PED_DEATHS']: measurements['ratio'],
}
rv_descriptions = {
    rv_keys['SEASON']: 'The annual surveillance cycle starting in summer (MMWR week 26).',
    rv_keys['AGE_GRP']: 'Demographic segments: 0-17 years, 18-64 years, and 65+ years.',
    rv_keys['RPHO_REGION']: 'The six California Regional Public Health Office areas or the whole state.',
    rv_keys['WEEKENDING']: 'The Saturday date marking the end of the CDC reporting week.',
    rv_keys['MMWR_WEEK']: 'Standardized CDC week number (1 to 52 or 53).',
    rv_keys['MMWR_YEAR']: 'The calendar year associated with the reporting week.',
    rv_keys['COV_POSITIVES']: 'Count of positive COVID-19 lab tests for the week.',
    rv_keys['COV_TOTAL_TESTS']: 'Total volume of COVID-19 lab tests performed.',
    rv_keys['COV_TP']: 'The percentage of COVID-19 tests that were positive. The formula is (COV_POSITIVES / COV_TOTAL_TESTS) * 100',
    rv_keys['COV_TP_LEVEL']: 'Positivity level based on 5 seasons of COVID-19 data.',
    rv_keys['FLU_POSITIVES']: 'Count of positive Influenza lab tests for the week.',
    rv_keys['FLU_TOTAL_TESTS']: 'Total volume of Influenza lab tests performed.',
    rv_keys['FLU_TP']: 'The percentage of Influenza tests that were positive. The formula is (FLU_POSITIVES / FLU_TOTAL_TESTS) * 100',
    rv_keys['FLU_TP_LEVEL']: 'Positivity level based on 5 seasons of Influenza data.',
    rv_keys['RSV_POSITIVES']: 'Count of positive RSV lab tests for the week.',
    rv_keys['RSV_TOTAL_TESTS']: 'Total volume of RSV lab tests performed.',
    rv_keys['RSV_TP']: 'The percentage of RSV tests that were positive. The formula is (RSV_POSITIVES / RSV_TOTAL_TESTS) * 100',
    rv_keys['RSV_TP_LEVEL']: 'Positivity level based on 5 seasons of RSV data.',
    rv_keys['FLU_A_TESTS']: 'Weekly count of positive tests for Influenza Type A.',
    rv_keys['FLU_B_TESTS']: 'Weekly count of positive tests for Influenza Type B.',
    rv_keys['COV_ED_VISITS']: 'Percentage of all ER visits related to COVID-19 symptoms.',
    rv_keys['FLU_ED_VISITS']: 'Percentage of all ER visits related to Influenza symptoms.',
    rv_keys['RSV_ED_VISITS']: 'Percentage of all ER visits related to RSV symptoms.',
    rv_keys['POP']: 'Regional population estimates used for rate calculations.',
    rv_keys['COV_ADM']: 'New weekly hospital admissions for COVID-19 (NHSN data).',
    rv_keys['FLU_ADM']: 'New weekly hospital admissions for Influenza (NHSN data).',
    rv_keys['RSV_ADM']: 'New weekly hospital admissions for RSV (NHSN data).',
    rv_keys['COV_ADM_RATE']: 'Weekly rate of COVID-19 admissions based on regional population.',
    rv_keys['FLU_ADM_RATE']: 'Weekly rate of Influenza admissions based on regional population.',
    rv_keys['RSV_ADM_RATE']: 'Weekly rate of RSV admissions based on regional population.',
    rv_keys['COV_ADM_LEVEL']: 'Admission level based on 5 seasons of COVID-19 positivity data.',
    rv_keys['FLU_ADM_LEVEL']: 'Admission level based on 5 seasons of Influenza positivity data.',
    rv_keys['RSV_ADM_LEVEL']: 'Admission level based on 5 seasons of RSV positivity data.',
    rv_keys['TOTAL_DEATHS']: 'Number of all-cause deaths each week.',
    rv_keys['COV_DEATHS']: 'Number of COVID-19 associated deaths each week.',
    rv_keys['FLU_DEATHS']: 'Number of influenza-associated deaths each week.',
    rv_keys['RSV_DEATHS']: 'Number of RSV-associated deaths each week.',
    rv_keys['COV_DEATHS_PER']: 'Percentage of all-cause deaths attributed to COVID-19.',
    rv_keys['FLU_DEATHS_PER']: 'Percentage of all-cause deaths attributed to Influenza.',
    rv_keys['RSV_DEATHS_PER']: 'Percentage of all-cause deaths attributed to RSV.',
    rv_keys['SEASON_COV_PED_DEATHS']: 'Number of COVID-19 associated pediatric deaths with lab-confirmation each week.',
    rv_keys['SEASON_FLU_PED_DEATHS']: 'Number of influenza-associated pediatric deaths with lab-confirmation each week.',
    rv_keys['SEASON_RSV_PED_DEATHS']: 'Number of RSV-associated pediatric deaths with lab-confirmation each week.',
}

rv.info()
pd.DataFrame({
    "Measurement Type": rv_measurements,
    "Description": rv_descriptions,
})

<class 'pandas.core.frame.DataFrame'>
Index: 140 entries, 16 to 3923
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SEASON                 140 non-null    object
 1   AGE_GRP                140 non-null    object
 2   RPHO_REGION            140 non-null    object
 3   WEEKENDING             140 non-null    object
 4   MMWR_WEEK              140 non-null    int64
 5   MMWR_YEAR              140 non-null    int64
 6   COV_POSITIVES          140 non-null    int64
 7   COV_TOTAL_TESTS        140 non-null    int64
 8   COV_TP                 140 non-null    float64
 9   COV_TP_LEVEL           140 non-null    object
 10  FLU_POSITIVES          140 non-null    int64
 11  FLU_TOTAL_TESTS        140 non-null    int64
 12  FLU_TP                 140 non-null    float64
 13  FLU_TP_LEVEL           140 non-null    object
 14  RSV_POSITIVES          140 non-null    int64
 15  RSV_TOTAL_TESTS        140 non-null    int64
 16  RSV_TP                 140 non-null    float64
 17  RSV_TP_LEVEL           140 non-null    object
 18  FLU_A_TESTS            34 non-null     float64
 19  FLU_B_TESTS            34 non-null     float64
 20  COV_ED_VISITS          0 non-null      float64
 21  FLU_ED_VISITS          0 non-null      float64
 22  RSV_ED_VISITS          0 non-null      float64
 23  POP                    112 non-null    float64
 24  COV_ADM                112 non-null    float64
 25  FLU_ADM                70 non-null     float64
 26  RSV_ADM                70 non-null     float64
 27  COV_ADM_RATE           112 non-null    float64
 28  FLU_ADM_RATE           70 non-null     float64
 29  RSV_ADM_RATE           70 non-null     float64
 30  COV_ADM_LEVEL          112 non-null    object
 31  FLU_ADM_LEVEL          70 non-null     object
 32  RSV_ADM_LEVEL          70 non-null     object
 33  TOTAL_DEATHS           140 non-null    float64
 34  COV_DEATHS             140 non-null    int64
 35  FLU_DEATHS             140 non-null    int64
 36  RSV_DEATHS             140 non-null    int64
 37  COV_DEATHS_PER         140 non-null    float64
 38  FLU_DEATHS_PER         140 non-null    float64
 39  RSV_DEATHS_PER         140 non-null    float64
 40  SEASON_COV_PED_DEATHS  0 non-null      float64
 41  SEASON_FLU_PED_DEATHS  0 non-null      float64
 42  SEASON_RSV_PED_DEATHS  0 non-null      float64
dtypes: float64(22), int64(11), object(10)
memory usage: 48.1+ KB

,Measurement Type,Description
SEASON,nominal,The annual surveillance cycle starting in summ...
AGE_GRP,nominal,"Demographic segments: 0-17 years, 18-64 years,..."
RPHO_REGION,nominal,The six California Regional Public Health Offi...
WEEKENDING,interval,The Saturday date marking the end of the CDC r...
MMWR_WEEK,interval,Standardized CDC week number (1 to 52 or 53).
MMWR_YEAR,interval,The calendar year associated with the reportin...
COV_POSITIVES,ratio,Count of positive COVID-19 lab tests for the w...
COV_TOTAL_TESTS,ratio,Total volume of COVID-19 lab tests performed.
COV_TP,ratio,The percentage of COVID-19 tests that were pos...
COV_TP_LEVEL,ordinal,Positivity level based on 5 seasons of COVID-1...
FLU_POSITIVES,ratio,Count of positive Influenza lab tests for the ...
FLU_TOTAL_TESTS,ratio,Total volume of Influenza lab tests performed.
FLU_TP,ratio,The percentage of Influenza tests that were po...
FLU_TP_LEVEL,ordinal,Positivity level based on 5 seasons of Influen...
RSV_POSITIVES,ratio,Count of positive RSV lab tests for the week.
RSV_TOTAL_TESTS,ratio,Total volume of RSV lab tests performed.
RSV_TP,ratio,The percentage of RSV tests that were positive...
RSV_TP_LEVEL,ordinal,Positivity level based on 5 seasons of RSV data.
FLU_A_TESTS,ratio,Weekly count of positive tests for Influenza T...
FLU_B_TESTS,ratio,Weekly count of positive tests for Influenza T...
COV_ED_VISITS,ratio,Percentage of all ER visits related to COVID-1...
FLU_ED_VISITS,ratio,Percentage of all ER visits related to Influen...
RSV_ED_VISITS,ratio,Percentage of all ER visits related to RSV sym...
POP,ratio,Regional population estimates used for rate ca...
COV_ADM,ratio,New weekly hospital admissions for COVID-19 (N...
FLU_ADM,ratio,New weekly hospital admissions for Influenza (...
RSV_ADM,ratio,New weekly hospital admissions for RSV (NHSN d...
COV_ADM_RATE,ratio,Weekly rate of COVID-19 admissions based on re...
FLU_ADM_RATE,ratio,Weekly rate of Influenza admissions based on r...
RSV_ADM_RATE,ratio,Weekly rate of RSV admissions based on regiona...
COV_ADM_LEVEL,ordinal,Admission level based on 5 seasons of COVID-19...
FLU_ADM_LEVEL,ordinal,Admission level based on 5 seasons of Influenz...
RSV_ADM_LEVEL,ordinal,Admission level based on 5 seasons of RSV posi...
TOTAL_DEATHS,ratio,Number of all-cause deaths each week.
COV_DEATHS,ratio,Number of COVID-19 associated deaths each week.
FLU_DEATHS,ratio,Number of influenza-associated deaths each week.
RSV_DEATHS,ratio,Number of RSV-associated deaths each week.
COV_DEATHS_PER,ratio,Percentage of all-cause deaths attributed to C...
FLU_DEATHS_PER,ratio,Percentage of all-cause deaths attributed to I...
RSV_DEATHS_PER,ratio,Percentage of all-cause deaths attributed to RSV.
SEASON_COV_PED_DEATHS,ratio,Number of COVID-19 associated pediatric deaths...
SEASON_FLU_PED_DEATHS,ratio,Number of influenza-associated pediatric death...
SEASON_RSV_PED_DEATHS,ratio,Number of RSV-associated pediatric deaths with...

## Pre-narrow respiratory virus data features
Based on feature descriptions, identify which features are unnecessary, and remove them to focus on relevant features and avoid wasting time.

In [103]:
rv = rv.drop([
    rv_keys['AGE_GRP'], # Dropped because we only keep 'All Ages' group.
    rv_keys['RPHO_REGION'], # Dropped because we only keep 'Bay Area' region.
    rv_keys['COV_ED_VISITS'], # Dropped because all data are NaN.
    rv_keys['FLU_ED_VISITS'], # Dropped because all data are NaN.
    rv_keys['RSV_ED_VISITS'], # Dropped because all data are NaN.
    rv_keys['SEASON_COV_PED_DEATHS'], # Dropped because all data are NaN.
    rv_keys['SEASON_FLU_PED_DEATHS'], # Dropped because all data are NaN.
    rv_keys['SEASON_RSV_PED_DEATHS'], # Dropped because all data are NaN.
], axis=1)

rv_measurements = {key: rv_measurements[key] for key in rv.columns if key in rv_measurements}
rv_descriptions = {key: rv_descriptions[key] for key in rv.columns if key in rv_descriptions}

rv_preview = rv.copy()
rv_preview['null_count'] = rv_preview.isnull().sum(axis=1)
rv_preview.sort_values('null_count', ascending=True).head(3).drop('null_count', axis=1)

,SEASON,WEEKENDING,MMWR_WEEK,MMWR_YEAR,COV_POSITIVES,COV_TOTAL_TESTS,COV_TP,COV_TP_LEVEL,FLU_POSITIVES,FLU_TOTAL_TESTS,...,COV_ADM_LEVEL,FLU_ADM_LEVEL,RSV_ADM_LEVEL,TOTAL_DEATHS,COV_DEATHS,FLU_DEATHS,RSV_DEATHS,COV_DEATHS_PER,FLU_DEATHS_PER,RSV_DEATHS_PER
3923,2025/2026,02/21/2026,7,2026,129,20264,0.636597,Very Low,2542,19212,...,Very Low,Low,Moderate,216.0,0,2,0,0.000000,0.925926,0.0
3336,2025/2026,10/04/2025,40,2025,777,17035,4.561198,Low,160,10707,...,Very Low,Very Low,Very Low,979.0,11,0,0,1.123596,0.000000,0.0
3322,2025/2026,09/27/2025,39,2025,1067,17896,5.962226,Low,146,8671,...,Very Low,Very Low,Very Low,1027.0,20,0,0,1.947420,0.000000,0.0

# Assess respiratory virus features

Document anomalies such as missing and NaN values. This will be referenced when fixing the data.

In [104]:
rv_assessment = rv.copy()
rv_assessment = rv_assessment.map(lambda row: row.strip().lower() if isinstance(row, str) else row)

rv_null_counts = {}
rv_null_percentages = {}
rv_duplicates = {}
rv_duplicate_percentages = {}

for key in rv_assessment.columns:
    null_count = rv_assessment[key].isna().sum()
    rv_null_counts[key] = null_count

    null_percentage = round((null_count / len(rv_assessment)) * 100, 2)
    rv_null_percentages[key] = null_percentage

    duplicates = rv_assessment[key].duplicated()
    duplicate_count = duplicates.sum()
    rv_duplicates[key] = duplicate_count

    duplicate_percentage = round((duplicate_count / len(rv_assessment)) * 100, 2)
    rv_duplicate_percentages[key] = duplicate_percentage

pd.DataFrame({
    'Null Count': rv_null_counts,
    'Null Percentage': rv_null_percentages,
    'Measurement Type': rv_measurements,
    'Duplicate Count': rv_duplicates,
    'Duplicate Percentage': rv_duplicate_percentages
})

,Null Count,Null Percentage,Measurement Type,Duplicate Count,Duplicate Percentage
SEASON,0,0.00,nominal,137,97.86
WEEKENDING,0,0.00,interval,2,1.43
MMWR_WEEK,0,0.00,interval,87,62.14
MMWR_YEAR,0,0.00,interval,136,97.14
COV_POSITIVES,0,0.00,ratio,6,4.29
COV_TOTAL_TESTS,0,0.00,ratio,1,0.71
COV_TP,0,0.00,ratio,0,0.00
COV_TP_LEVEL,0,0.00,ordinal,136,97.14
FLU_POSITIVES,0,0.00,ratio,11,7.86
FLU_TOTAL_TESTS,0,0.00,ratio,0,0.00
FLU_TP,0,0.00,ratio,0,0.00
FLU_TP_LEVEL,0,0.00,ordinal,135,96.43
RSV_POSITIVES,0,0.00,ratio,22,15.71
RSV_TOTAL_TESTS,0,0.00,ratio,0,0.00
RSV_TP,0,0.00,ratio,0,0.00
RSV_TP_LEVEL,0,0.00,ordinal,135,96.43
FLU_A_TESTS,106,75.71,ratio,106,75.71
FLU_B_TESTS,106,75.71,ratio,115,82.14
POP,28,20.00,ratio,135,96.43
COV_ADM,28,20.00,ratio,32,22.86
FLU_ADM,70,50.00,ratio,81,57.86
RSV_ADM,70,50.00,ratio,88,62.86
COV_ADM_RATE,28,20.00,ratio,32,22.86
FLU_ADM_RATE,70,50.00,ratio,78,55.71
RSV_ADM_RATE,70,50.00,ratio,86,61.43
COV_ADM_LEVEL,28,20.00,ordinal,137,97.86
FLU_ADM_LEVEL,70,50.00,ordinal,134,95.71
RSV_ADM_LEVEL,70,50.00,ordinal,134,95.71
TOTAL_DEATHS,0,0.00,ratio,34,24.29
COV_DEATHS,0,0.00,ratio,103,73.57
FLU_DEATHS,0,0.00,ratio,119,85.00
RSV_DEATHS,0,0.00,ratio,130,92.86
COV_DEATHS_PER,0,0.00,ratio,4,2.86
FLU_DEATHS_PER,0,0.00,ratio,45,32.14
RSV_DEATHS_PER,0,0.00,ratio,76,54.29

## Notes
- Found duplicate WEEKENDING with value 12/28/2024.